name: Replace Secrets on Pull

on:
  push:
    branches: [ main, one-artifact-folder ]
    paths: 
      - 'Fabric_artifacts/**'
  pull_request:
    branches: [ main, one-artifact-folder ]
    paths: 
      - 'Fabric_artifacts/**'

jobs:
  replace-secrets:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Replace secrets in template
      env:
        FABRIC_SQL_CONNECTION_STRING: ${{ secrets.FABRIC_SQL_CONNECTION_STRING }}
        FABRIC_LAKEHOUSE_GUID: ${{ secrets.FABRIC_LAKEHOUSE_GUID }}
      run: |
        # Replace placeholders with actual secrets
        sed "s|__FABRIC_SQL_CONNECTION_STRING__|$FABRIC_SQL_CONNECTION_STRING|g" \
            Fabric_artifacts/agentic_semantic_model.SemanticModel/definition/expressions.template.tmdl | \
        sed "s|__FABRIC_LAKEHOUSE_GUID__|$FABRIC_LAKEHOUSE_GUID|g" > \
            Fabric_artifacts/agentic_semantic_model.SemanticModel/definition/expressions.tmdl
        
        echo "✅ Secrets replaced successfully"
    
    - name: Show result (for verification)
      run: |
        echo "Generated expressions.tmdl:"